version: '3' # docker compose version

services:
    django_game:
        image: django_game
        container_name: django_game
        pull_policy: never # dockerhub등에서 이미지 받아오지 않음
        build:
            context: ./game/ # Dockerfile folder
            dockerfile: Dockerfile
        ports:
            - "8000:8000" # host 8000 port로 연결
        networks:
            - ts-network
        restart: always # 시스템 부팅 및 오류로 인한 실패 시 컨테이너 재시작
        env_file: .env

networks:
    ts-network:
        # transcendence network 생성
        driver: bridge # bridge driver, 호스트에 노출되지 않는 네트워크를 생성

