name: Update and Build

on:
  push:
    branches:
      - main

jobs:
  update_and_build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

  

    - name: SSH into GCP Instance
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.GCP_INSTANCE_IP }}
        username: ${{ secrets.GCP_INSTANCE_USERNAME }}
        key: ${{ secrets.GCP_INSTANCE_SSH_KEY }}
        port: ${{ secrets.GCP_INSTANCE_SSH_PORT }}

    - name: Pull Latest Changes
      run: |
        cd Transcendence_Backend
        git pull

    - name: Run Make
      run: |
        Transcendence_Backend
        make re
